version: '3.8'

services:
  auth:
    build: ./AuthenticationService
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
    networks:
      - mynetwork
  global:
    build: ./GlobalTasksService
    ports:
      - "8081:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
    networks:
      - mynetwork
  user:
    build: ./UserTasksService
    ports:
      - "8082:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
    networks:
      - mynetwork

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge